name: bare SSH Github-runner ARM
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x ./setup-ssh-arm
      - run: echo ${{ secrets.GH_TOKEN }} > ghtoken.txt
      - run: sudo gh auth login --with-token < ghtoken.txt
      - run: rm ghtoken.txt
      - run: sudo mkdir /mnt/runner-will-upload
      - run: sudo rm -f /mnt/DATALOSS_WARNING_README.txt
      - run: sudo apt update
      - run: sudo apt install qemu-kvm nano pbzip2 -y
      - run: $GITHUB_WORKSPACE/setup-ssh-arm
        shell: bash
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: arts
          path: /mnt/runner-will-upload/*
