name: bare SSH Github-runner
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x ./setup-ssh
      - run: sudo mkdir /mnt/runner-will-upload
      - run: sudo rm -f /mnt/DATALOSS_WARNING_README.txt
      - run: sudo apt update
      - run: sudo apt install qemu-kvm nano -y
      - run: $GITHUB_WORKSPACE/setup-ssh
        shell: bash
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: arts
          path: /mnt/runner-will-upload/*
          
